### ISSUE TITLE
Server crashes upon player death

### ISSUE THREAD

**Issue by SageofTurtles** [Salandora/SophisticatedBackpacks#19]
**Describe the bug**
We're using this mod in our modpack on my server.  After the update today, we installed it, but two players have died since, and both instances immediately caused our server to crash.  One of the players attempted to re-join when the server restarted, but this caused it to crash again, citing an "Exception Ticking World".  The crash reports mention Trinkets, so there may be some incompatibility there.  We also have the Gravestones mod installed, which may be related to the issue.  Crash reports are attached.

**To Reproduce**
1. Install the modpack listed in the "Mods List.txt" file (attached) on a server
2. Open the world, and give a player the backpack.
3. Kill the player.
4. Server crashes upon player death, and that player's attempts to re-join.

**Expected behavior**
Expected that the player would die and the backpack and other items in their inventory would be placed into the gravestone.

**Versions**
Using Fabric Loader 0.15.11, and all mods are included in the "Mods List.txt" file attached.

[Mods List.txt](https://github.com/Salandora/SophisticatedBackpacks/files/15445230/Mods.List.txt)

[1st-crash.txt](https://github.com/Salandora/SophisticatedBackpacks/files/15445227/1st-crash.txt)
[2nd-crash.txt](https://github.com/Salandora/SophisticatedBackpacks/files/15445228/2nd-crash.txt)
[3rd-crash.txt](https://github.com/Salandora/SophisticatedBackpacks/files/15445229/3rd-crash.txt)

**Comment by littlebugkate** [comment]
I ran into this same problem last night on my single player world, with a similar crash log. I am also using trinkets and gravestones. I've done a little bit of testing, and found out:

1. The game always crashes on death if I have a backpack in the trinket slot.
2. The game always crashes on death if I have gravestone drop type to put_in_inventory.

If I have the backpack in my inventory slots, and the gravestone drop type as drop_items, it crashes sometimes but not every time. I haven't figured out why it doesn't always work. The gravestone mod doesn't seem to have the best support for trinkets, as my trinket items were falling on the ground rather than staying in the gravestone. It only crashes with the equipped backpack. 

I think I'm going to switch to the gravestone datapack on vanilla tweaks. It's not perfect either, as you don't lose the stuff in your trinket slots upon death, but there's no accidental deletion or crashing.

**Comment by Salandora** [comment]
Working on a fix for that.
Have an idea what is causing it.

**Comment by Salandora** [comment]
Also interesting you two are talking about 2 different gravestone mods I think. 
@littlebugkate can you link the one you used?

**Comment by littlebugkate** [comment]
@Salandora oh shit u right, I didn't look at op's mod list close enough. I was using [gravestones by geometrically](https://modrinth.com/mod/gravestones/version/v1.15). sorry about that!

**Comment by Shadowbee27** [comment]
With the mod [You are in Grave danger](https://modrinth.com/mod/yigd) the game doesn´t crash when a player is killed.

**Comment by Salandora** [comment]
Fixed in f6072fbf7151a6d19c3d4ab933fc841696573644

**Comment by SageofTurtles** [comment]
Thank you! Everyone on my server (and myself) has been looking forward to adding this mod since we heard there was a Fabric port. We're very grateful for your efforts!

**Comment by Salandora** [comment]
Bugfix release is out.
